# loan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan
  labels:
    app: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: devopsxkeepcoding/martian-bank:loan-1.3.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: configmap-martianbank
          env:
            - name: SERVICE_PROTOCOL
              value: {{.Values.SERVICE_PROTOCOL}}
          livenessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      nodeSelector:   
        {{- if .Values.nodeSelector.enabled }}
          role: {{ .Values.nodeSelector.role }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
    name: loan
spec:
    selector:
        app: loan
    ports:
        - protocol: TCP
          port: 50053
          targetPort: 50053
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loan-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loan
  minReplicas: {{ .Values.autoscaling.minReplicas }} # Minimum number of pods to maintain
  maxReplicas: {{ .Values.autoscaling.maxReplicas }} # Maximum number of pods to scale up to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Scale up if CPU usage reaches 50% on average
{{- end }}