# locust
{{- if .Values.locust.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: locust
    labels:
        app: locust
spec:
    replicas: 1
    selector:
        matchLabels:
            app: locust
    template:
        metadata:
            labels:
                app: locust
        spec:
            containers:
                - name: locust
                  image: ghcr.io/cisco-open/martian-bank-demo-performance_locust
                  env:
                    - name: VITE_USERS_URL
                      value: http://customer-auth:8000/api/users
                    - name: VITE_ATM_URL
                      value: http://atm-locator:8001/api/atm
                    - name: VITE_ACCOUNTS_URL
                      value: http://dashboard:5000/account
                    - name: VITE_TRANSFER_URL
                      value: http://dashboard:5000/transaction
                    - name: VITE_LOAN_URL
                      value: http://dashboard:5000/loan
---
apiVersion: v1
kind: Service
metadata:
    name: locust
spec:
    selector:
        app: locust
    ports:
        - protocol: TCP
          port: 8098
          targetPort: 8098
{{- end }}