apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  mongodb-root-username: cm9vdA==
  mongodb-root-password: ZXhhbXBsZQ==
  database-host: bW9uZ29kYg==
  webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4ME01NFRKSEUvQjA3VkNDSEdDMTAvVHR1UWpzcFFkQm5Nd3VwMVpTWTRCQU5Q
