---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: transactions
    labels:
        app: transactions
spec:
    replicas: 1
    selector:
        matchLabels:
            app: transactions
    template:
        metadata:
            labels:
                app: transactions
        spec:
            containers:
                - name: transactions
                  image: devopsxkeepcoding/transactions:latest
                  imagePullPolicy: IfNotPresent
                  envFrom:
                    - configMapRef:
                        name: configmap-martianbank
                  env:
                    - name: SERVICE_PROTOCOL
                      value: {{.Values.SERVICE_PROTOCOL}}      
                  livenessProbe:
                    tcpSocket:
                        port: 50052
                    initialDelaySeconds: 10
                    periodSeconds: 20
                  readinessProbe:
                    tcpSocket:
                        port: 50052
                    initialDelaySeconds: 10
                    periodSeconds: 20
                  resources:
                    requests:
                      memory: {{ .Values.resources.requests.memory }}
                      cpu: {{ .Values.resources.requests.cpu }}
                    limits:
                      memory: {{ .Values.resources.limits.memory }}
                      cpu: {{ .Values.resources.limits.cpu }}
            nodeSelector:   
              {{- if .Values.nodeSelector.enabled }}
                role: {{ .Values.nodeSelector.role }}
              {{- end }}
---
apiVersion: v1
kind: Service
metadata:
    name: transactions
spec:
    selector:
        app: transactions
    ports:
        - protocol: TCP
          port: 50052
          targetPort: 50052
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transactions-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactions
  minReplicas: 1 # Minimum number of pods to maintain
  maxReplicas: 5 # Maximum number of pods to scale up to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Scale up if CPU usage reaches 50% on average
