apiVersion: v1
kind: Secret
metadata:
  name: martianbanktest-mongodb-secret
  namespace: default
type: Opaque
data:
  database-host: bW9uZ29kYg==
  mongodb-root-password: ZXhhbXBsZQ==
  mongodb-root-username: cm9vdA==
  webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4ME01NFRKSEUvQjA3VkNDSEdDMTAvVHR1UWpzcFFkQm5Nd3VwMVpTWTRCQU5Q
